#访问路径
server:
  port: 9091
  servlet:
    context-path: /myproject

#自定义属性
boot:
  name: 张三

#web返回后添加前后缀
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

      #数据库连接信息
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.173:3306/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

#mybatis的mapper配置文件
mybatis:
  mapper-locations: classpath:com/example/springboot/mapper/*.xml

